### ISSUE TITLE
Sometimes inconsistent?

### ISSUE THREAD

**Issue by manstie** [kindone/text-versioncontrol#2]
How to reproduce:

1. Go to https://codepen.io/manstie/pen/wvWRgRW
2. Adjust NETWORK_DELAY to your liking
3. Create multiple lines by pressing enter
4. Type something in the first line on the left editor
5. While nothing has appeared in the right editor, type something else on another line
![image](https://user-images.githubusercontent.com/12475567/98921742-5ed18200-251d-11eb-9e56-b6af7cf0bad5.png)
Is it something wrong with text-versioncontrol or with my code?

**Comment by kindone** [comment]
Hi manstie,

I haven't checked your code fully,  but you are incorrectly using SharedString::applyChange. 

You should do in case of an event received from other uid:  editor.get(my_uid).ss.applyChange(delta, other_uid)
But you are calling it as: editor.get(my_uid).ss.applyChange(delta, my_uid)

Best regards

**Comment by kindone** [comment]
I'll close this as invalid
